"""
Pydantic Request/Response Schema Validation Layer for FastAPI Deployment.
Implements structural validation rules for real-time risk scoring applications.
"""

from pydantic import BaseModel, Field

class CreditInferenceRequest(BaseModel):
    """
    Validates transactional parameters submitted for underwriting evaluations.
    """
    transaction_id: str = Field(..., description="Unique alphanumeric identifier for transaction telemetry.")
    amount: float = Field(..., gt=0, description="Transaction monetary value in UGX. Must exceed zero.")
    value: float = Field(..., gt=0, description="Absolute asset magnitude value. Must exceed zero.")
    transaction_velocity_1h: int = Field(default=1, ge=0, description="Volume of transaction sequences within past hour.")

    class Config:
        json_schema_extra = {
            "example": {
                "transaction_id": "TX_99831_UG",
                "amount": 5000.0,
                "value": 5000.0,
                "transaction_velocity_1h": 2
            }
        }

class CreditInferenceResponse(BaseModel):
    """
    Defines structural layout protocols for API responses.
    """
    transaction_id: str
    risk_probability: float = Field(..., ge=0.0, le=1.0, description="Calculated model underwriting risk density vector score.")
    is_high_risk: bool = Field(..., description="Binary proxy decision flag generated by optimization layer threshholds.") 
